# Generated by Django 2.0.2 on 2018-02-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
                'ordering': ['created', 'modified'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('ref', models.CharField(max_length=10, verbose_name='Reference')),
                ('symbol', models.CharField(blank=True, max_length=20, null=True, verbose_name='symbol')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'sensor',
                'verbose_name_plural': 'sensors',
                'ordering': ['created', 'modified'],
            },
        ),
        migrations.AddField(
            model_name='log',
            name='sensor',
            field=models.ForeignKey(on_delete=None, to='website.Sensor'),
        ),
    ]
