# Generated by Django 2.0.2 on 2018-02-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='colour',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Colour'),
        ),
    ]
